### ISSUE TITLE
Add Diglot View

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-ios#12]
User should be able to select 2 languages to view at the same time.

**Comment by bknatterud** [comment]
This is working fine on the Bible, but we're wondering about OBS. In landscape I'm not sure what is the best way to do it without covering a lot of the image. But is that is ok we can do it.

**Comment by jag3773** [comment]
I was thinking side by side at the bottom, e.g.

Image
Text lang 1 | Text lang 2

Will still probably cover more of the image but may be better?

**Comment by dwsolberg** [comment]
This is done.
