### ISSUE TITLE
Add Chromecast Support

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-ios#13]
App should be able to pipe content to Chromecast to show on big screens.

**Comment by bknatterud** [comment]
I'm wondering what content you are hoping to be able to put up on a TV screen from uW using Chromecast. On iOS simply mirroring the screen would be a pretty significant effort. So what are you hoping for with this?

**Comment by jag3773** [comment]
Text, audio, and/or video.

**Comment by dwsolberg** [comment]
Chromecast isn't really made for screen sharing. The original idea was that it would basically be an internet url that would have an audio or video file to play. It's more advanced now, but still not a mirror of the screen. We'll need to discuss ways to make this work as well as possible.
