### ISSUE TITLE
App Jumps Straight to Text

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-ios#17]
After initial install the app should present a list of versions to choose from when OBS or Bible is selected, currently it jumps straight into the text.

**Comment by dwsolberg** [comment]
After the initial install, it goes to the main menu. After subsequent uses, it returns to the bible/chapter the user was last viewing.

**Comment by dwsolberg** [comment]
If you would like the app to always start at the main menu, let me know and I'll make that change.

**Comment by jag3773** [comment]
On a fresh install I am not taken to the version list when I select either Bible or OBS.  Rather, I'm taken directly into the UDB for Bible or the English version of OBS.  If I have yet to select a version within a project then I should be prompted to select one first.
