### ISSUE TITLE
Remove Extra Lines in Menus

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-ios#20]
In the Settings screen and also the chapter list screen there are lines on the page past the settings list.  For example, Lamentations has 5 chapters but there are roughly 20 line dividers on the chapter list for Lamentations.

**Comment by dwsolberg** [comment]
Changed on chapter list. Will change on settings page.

**Comment by dwsolberg** [comment]
Changed settings page in commit 463ea60
