### ISSUE TITLE
Title Bar overlap on scroll

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/uw-ios#24]
When you scroll and the title bar shrinks much of the layout is overlapping and messy for a few seconds. Seems to take a while to redraw itself?

The book name appears over the Time for a brief moment.
The back arrow lingers a while longer being faded and cropped off.

**Comment by dwsolberg** [comment]
I'm not getting the book name going over the time, but I do see the issue with the back arrow.

**Comment by dwsolberg** [comment]
These two issues are fixed. However, there is some odd jumping around in some situations that I can't seem to pin down.
