### ISSUE TITLE
Top align OBS Text

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/uw-ios#25]
In OBS the text for each section/image should be directly underneath the image. This avoids the start line being at different heights on each screen. It also avoids the varying large green space.

**Comment by dwsolberg** [comment]
So you want the text to be top aligned maybe 10 points below the image, and if the text is too long, you want it to scroll? It should no longer cover any part of the image.

Is all this correct?

**Comment by sampeckham** [comment]
See: https://github.com/unfoldingWord-dev/uw-ios/issues/26
