### ISSUE TITLE
OBS - Dark background under image

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/uw-ios#26]
The whole background below the image should be the same color, even when there is no text. This should be the darker color the text is current over.

**Comment by dwsolberg** [comment]
Not completely sure what this means. Could you provide an image of what should change?

**Comment by sampeckham** [comment]
Quick mock up from a screenshot:
![screen shot 2015-10-14 at 15 28 25](https://cloud.githubusercontent.com/assets/323212/10486736/405d7dbc-7288-11e5-989b-cd09af8266c8.png)

**Comment by dwsolberg** [comment]
Let me know how you want to handle landscape. Here's an example of a pretty typical landscape OBS frame:

![side-by-side obs landscape](https://cloud.githubusercontent.com/assets/599596/10520090/2f4608cc-732e-11e5-965a-02fe6bab698f.png)

**Comment by dwsolberg** [comment]
This probably needs some tweaking in landscape mode, but it's otherwise done.
