### ISSUE TITLE
Back arrow too large.

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/uw-ios#28]
The back arrow is too large compared with iOs standard.
![screen shot 2015-10-13 at 17 50 06](https://cloud.githubusercontent.com/assets/323212/10461753/dbe6e126-71d2-11e5-9edf-670f3324e7fe.png)

**Comment by dwsolberg** [comment]
Could you send a PDF with the arrow in the size you would like? Attached is the original PDF we received for reference.
[Arrow.pdf](https://github.com/unfoldingWord-dev/uw-ios/files/12614/Arrow.pdf)

**Comment by sampeckham** [comment]
So far as i can tell the original arrow was just at @2x. Here's the arrow at @1x. Should work. 
[arrow@1x.pdf](https://github.com/unfoldingWord-dev/uw-ios/files/13276/arrow.1x.pdf)

**Comment by dwsolberg** [comment]
@sampeckham Thanks for the arrow. iOS can be confusing, but when we're using a PDF, the size should also be the 1x size because it's resolution independent. (If we were using a PNG file, we would need 1x, 2x and 3x versions)
